/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as HelpImport } from './routes/help'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectsIndexImport } from './routes/projects.index'
import { Route as ProjectsProjectIdIndexImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdTracesImport } from './routes/projects.$projectId.traces'
import { Route as ProjectsProjectIdLogsImport } from './routes/projects.$projectId.logs'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const HelpRoute = HelpImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsIndexRoute = ProjectsIndexImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectIdTracesRoute = ProjectsProjectIdTracesImport.update({
  id: '/projects/$projectId/traces',
  path: '/projects/$projectId/traces',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectIdLogsRoute = ProjectsProjectIdLogsImport.update({
  id: '/projects/$projectId/logs',
  path: '/projects/$projectId/logs',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId/logs': {
      id: '/projects/$projectId/logs'
      path: '/projects/$projectId/logs'
      fullPath: '/projects/$projectId/logs'
      preLoaderRoute: typeof ProjectsProjectIdLogsImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId/traces': {
      id: '/projects/$projectId/traces'
      path: '/projects/$projectId/traces'
      fullPath: '/projects/$projectId/traces'
      preLoaderRoute: typeof ProjectsProjectIdTracesImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/settings': typeof SettingsRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/logs': typeof ProjectsProjectIdLogsRoute
  '/projects/$projectId/traces': typeof ProjectsProjectIdTracesRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/settings': typeof SettingsRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/logs': typeof ProjectsProjectIdLogsRoute
  '/projects/$projectId/traces': typeof ProjectsProjectIdTracesRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/settings': typeof SettingsRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/logs': typeof ProjectsProjectIdLogsRoute
  '/projects/$projectId/traces': typeof ProjectsProjectIdTracesRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/help'
    | '/settings'
    | '/projects'
    | '/projects/$projectId/logs'
    | '/projects/$projectId/traces'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/help'
    | '/settings'
    | '/projects'
    | '/projects/$projectId/logs'
    | '/projects/$projectId/traces'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/help'
    | '/settings'
    | '/projects/'
    | '/projects/$projectId/logs'
    | '/projects/$projectId/traces'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HelpRoute: typeof HelpRoute
  SettingsRoute: typeof SettingsRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdLogsRoute: typeof ProjectsProjectIdLogsRoute
  ProjectsProjectIdTracesRoute: typeof ProjectsProjectIdTracesRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HelpRoute: HelpRoute,
  SettingsRoute: SettingsRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdLogsRoute: ProjectsProjectIdLogsRoute,
  ProjectsProjectIdTracesRoute: ProjectsProjectIdTracesRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/help",
        "/settings",
        "/projects/",
        "/projects/$projectId/logs",
        "/projects/$projectId/traces",
        "/projects/$projectId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/help": {
      "filePath": "help.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/projects/": {
      "filePath": "projects.index.tsx"
    },
    "/projects/$projectId/logs": {
      "filePath": "projects.$projectId.logs.tsx"
    },
    "/projects/$projectId/traces": {
      "filePath": "projects.$projectId.traces.tsx"
    },
    "/projects/$projectId/": {
      "filePath": "projects.$projectId.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
