/**
 * This file is auto-generated by ioc-arise.
 * Do not modify this file manually.
 */
import { Container, Lifecycle } from '@notjustcoders/di-container';
import type { ContainerRegistry } from './container.gen.d';
import { UpdateTrace } from './use-cases/updateTrace';
import { UpdateSpan } from './use-cases/updateSpan';
import { UpdateProjectConfig } from './use-cases/updateProjectConfig';
import { UpdateProject } from './use-cases/updateProject';
import { StopServer } from './use-cases/stopServer';
import { StopMCPServer } from './use-cases/stopMCPServer';
import { SetConfig } from './use-cases/setConfig';
import { RestartServer } from './use-cases/restartServer';
import { RestartMCPServer } from './use-cases/restartMCPServer';
import { GetTracesByProjectId } from './use-cases/getTracesByProjectId';
import { GetTraceWithSpans } from './use-cases/getTraceWithSpans';
import { GetTraceById } from './use-cases/getTraceById';
import { GetSpansByTraceId } from './use-cases/getSpansByTraceId';
import { GetServerLogs } from './use-cases/getServerLogs';
import { GetProjectMetrics } from './use-cases/getProjectMetrics';
import { GetProjectConfig } from './use-cases/getProjectConfig';
import { GetProjectById } from './use-cases/getProjectById';
import { GetMetadataKeysByProjectId } from './use-cases/getMetadataKeysByProjectId';
import { GetMCPServerLogs } from './use-cases/getMCPServerLogs';
import { GetLogsByProjectId } from './use-cases/getLogsByProjectId';
import { GetLogById } from './use-cases/getLogById';
import { GetHistoricalLogCounts } from './use-cases/getHistoricalLogCounts';
import { GetFilteredLogs } from './use-cases/getFilteredLogs';
import { GetConfig } from './use-cases/getConfig';
import { GetAllProjects } from './use-cases/getAllProjects';
import { GetAllLogs } from './use-cases/getAllLogs';
import { GetAllConfig } from './use-cases/getAllConfig';
import { DeleteProject } from './use-cases/deleteProject';
import { CreateTrace } from './use-cases/createTrace';
import { CreateSpan } from './use-cases/createSpan';
import { CreateProject } from './use-cases/createProject';
import { CreateLog } from './use-cases/createLog';
import { CreateBulkLog } from './use-cases/createBulkLog';
import { ClearServerLogs } from './use-cases/clearServerLogs';
import { ClearProjectTraces } from './use-cases/clearProjectTraces';
import { ClearProjectLogs } from './use-cases/clearProjectLogs';
import { ClearMCPServerLogs } from './use-cases/clearMCPServerLogs';
import { BulkCreateTraces } from './use-cases/bulkCreateTraces';
import { WebServerManager } from './server/webServerManager';
import { ServerManager } from './server/serverManager';
import { ServerLogger } from './server/serverLogger';
import { MCPServerManager } from './server/mcpServerManager';
import { TraceRepository } from './repositories/traceRepository';
import { ProjectRepository } from './repositories/projectRepository';
import { LogRepository } from './repositories/logRepository';
import { ConfigRepository } from './repositories/configRepository';

declare global {
  var container: Container<ContainerRegistry>
}
export const container = globalThis.container || new Container<ContainerRegistry>();
globalThis.container = container;

container.register(UpdateTrace, {
  useClass: UpdateTrace,
  dependencies: [TraceRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(UpdateSpan, {
  useClass: UpdateSpan,
  dependencies: [TraceRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(UpdateProjectConfig, {
  useClass: UpdateProjectConfig,
  dependencies: [ProjectRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(UpdateProject, {
  useClass: UpdateProject,
  dependencies: [ProjectRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(StopServer, {
  useClass: StopServer,
  dependencies: [ServerManager],
  lifecycle: Lifecycle.Singleton,
});

container.register(StopMCPServer, {
  useClass: StopMCPServer,
  dependencies: [MCPServerManager],
  lifecycle: Lifecycle.Singleton,
});

container.register(SetConfig, {
  useClass: SetConfig,
  dependencies: [ConfigRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(RestartServer, {
  useClass: RestartServer,
  dependencies: [ServerManager],
  lifecycle: Lifecycle.Singleton,
});

container.register(RestartMCPServer, {
  useClass: RestartMCPServer,
  dependencies: [MCPServerManager],
  lifecycle: Lifecycle.Singleton,
});

container.register(GetTracesByProjectId, {
  useClass: GetTracesByProjectId,
  dependencies: [TraceRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(GetTraceWithSpans, {
  useClass: GetTraceWithSpans,
  dependencies: [TraceRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(GetTraceById, {
  useClass: GetTraceById,
  dependencies: [TraceRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(GetSpansByTraceId, {
  useClass: GetSpansByTraceId,
  dependencies: [TraceRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(GetServerLogs, {
  useClass: GetServerLogs,
  dependencies: [ServerManager],
  lifecycle: Lifecycle.Singleton,
});

container.register(GetProjectMetrics, {
  useClass: GetProjectMetrics,
  dependencies: [LogRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(GetProjectConfig, {
  useClass: GetProjectConfig,
  dependencies: [ProjectRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(GetProjectById, {
  useClass: GetProjectById,
  dependencies: [ProjectRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(GetMetadataKeysByProjectId, {
  useClass: GetMetadataKeysByProjectId,
  dependencies: [LogRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(GetMCPServerLogs, {
  useClass: GetMCPServerLogs,
  dependencies: [MCPServerManager],
  lifecycle: Lifecycle.Singleton,
});

container.register(GetLogsByProjectId, {
  useClass: GetLogsByProjectId,
  dependencies: [LogRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(GetLogById, {
  useClass: GetLogById,
  dependencies: [LogRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(GetHistoricalLogCounts, {
  useClass: GetHistoricalLogCounts,
  dependencies: [LogRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(GetFilteredLogs, {
  useClass: GetFilteredLogs,
  dependencies: [LogRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(GetConfig, {
  useClass: GetConfig,
  dependencies: [ConfigRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(GetAllProjects, {
  useClass: GetAllProjects,
  dependencies: [ProjectRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(GetAllLogs, {
  useClass: GetAllLogs,
  dependencies: [LogRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(GetAllConfig, {
  useClass: GetAllConfig,
  dependencies: [ConfigRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(DeleteProject, {
  useClass: DeleteProject,
  dependencies: [ProjectRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(CreateTrace, {
  useClass: CreateTrace,
  dependencies: [TraceRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(CreateSpan, {
  useClass: CreateSpan,
  dependencies: [TraceRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(CreateProject, {
  useClass: CreateProject,
  dependencies: [ProjectRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(CreateLog, {
  useClass: CreateLog,
  dependencies: [LogRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(CreateBulkLog, {
  useClass: CreateBulkLog,
  dependencies: [LogRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(ClearServerLogs, {
  useClass: ClearServerLogs,
  dependencies: [ServerManager],
  lifecycle: Lifecycle.Singleton,
});

container.register(ClearProjectTraces, {
  useClass: ClearProjectTraces,
  dependencies: [TraceRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(ClearProjectLogs, {
  useClass: ClearProjectLogs,
  dependencies: [LogRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(ClearMCPServerLogs, {
  useClass: ClearMCPServerLogs,
  dependencies: [MCPServerManager],
  lifecycle: Lifecycle.Singleton,
});

container.register(BulkCreateTraces, {
  useClass: BulkCreateTraces,
  dependencies: [TraceRepository, ProjectRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(WebServerManager, {
  useClass: WebServerManager,
  lifecycle: Lifecycle.Singleton,
});

container.register(ServerManager, {
  useClass: ServerManager,
  dependencies: [ConfigRepository],
  lifecycle: Lifecycle.Singleton,
});

container.register(ServerLogger, {
  useClass: ServerLogger,
  lifecycle: Lifecycle.Singleton,
});

container.register(MCPServerManager, {
  useClass: MCPServerManager,
  dependencies: [ConfigRepository, ServerLogger],
  lifecycle: Lifecycle.Singleton,
});

container.register(TraceRepository, {
  useClass: TraceRepository,
  lifecycle: Lifecycle.Singleton,
});

container.register(ProjectRepository, {
  useClass: ProjectRepository,
  lifecycle: Lifecycle.Singleton,
});

container.register(LogRepository, {
  useClass: LogRepository,
  lifecycle: Lifecycle.Singleton,
});

container.register(ConfigRepository, {
  useClass: ConfigRepository,
  lifecycle: Lifecycle.Singleton,
});
console.log("crashed here-------------" + ConfigRepository.name)
console.log(container.resolve(ConfigRepository.name));